version: '3.8'

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    image: project:latest
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - project-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - project-network

volumes:
  mongo-data:

networks:
  project-network:
